[versions]
agp = "8.13.0"
kotlin = "2.2.21"
ksp = "2.2.20-2.0.3"
jetpackWatchface = "1.3.0-alpha04"
composeWear = "1.5.5"
vectorDrawable = "1.2.0"
composeBom = "2025.11.00"
wearToolingPreview = "1.0.0"
activityCompose = "1.11.0"
coreSplashscreen = "1.2.0"
androidxAnnotation = "1.9.1"
koin = "4.1.1"
koinKsp = "2.2.21"

[libraries]
androidx-watchface = { group = "androidx.wear.watchface", name = "watchface", version.ref = "jetpackWatchface" }

# complications
androidx-watchface-complications-data-source = { group = "androidx.wear.watchface", name = "watchface-complications-data-source", version.ref = "jetpackWatchface" }
androidx-watchface-complications-data-source-ktx = { group = "androidx.wear.watchface", name = "watchface-complications-data-source-ktx", version.ref = "jetpackWatchface" }
androidx-watchface-complications-rendering = { group = "androidx.wear.watchface", name = "watchface-complications-rendering", version.ref = "jetpackWatchface" }

# watchface style and complication editor
androidx-watchface-editor = { group = "androidx.wear.watchface", name = "watchface-editor", version.ref = "jetpackWatchface" }
androidx-watchface-client = { group = "androidx.wear.watchface", name = "watchface-client", version.ref = "jetpackWatchface" }

# Jetpack Compose
androidx-wear-compose-foundation = { group = "androidx.wear.compose", name = "compose-foundation", version.ref = "composeWear" }
androidx-wear-compose-material = { group = "androidx.wear.compose", name = "compose-material", version.ref = "composeWear" }
androidx-wear-compose-material3 = { group = "androidx.wear.compose", name = "compose-material3", version.ref = "composeWear" }
androidx-wear-compose-navigation = { group = "androidx.wear.compose", name = "compose-navigation", version.ref = "composeWear" }

# others
androidx-vectordrawable = { group = "androidx.vectordrawable", name = "vectordrawable", version.ref = "vectorDrawable" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-wear-tooling-preview = { group = "androidx.wear", name = "wear-tooling-preview", version.ref = "wearToolingPreview" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "coreSplashscreen" }
androidx-annotation = { group = "androidx.annotation", name = "annotation-jvm", version.ref = "androidxAnnotation" }

koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koinKsp" }
koin-ksp-compiler = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koinKsp" }

#implementation(kotlin("reflect"))

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[bundles]
watchface-complications = ["androidx-watchface-complications-data-source", "androidx-watchface-complications-data-source-ktx", "androidx-watchface-complications-rendering"]
watchface-editor = ["androidx-watchface-editor", "androidx-watchface-client"]
jetpack-compose = ["androidx-wear-compose-foundation", "androidx-wear-compose-material", "androidx-wear-compose-material3", "androidx-wear-compose-navigation"]